name: mojo
version: '1.0.0'
config-version: 3

profile: mojo

model-paths: [models]
analysis-paths: [analyses]
test-paths: [tests]
seed-paths: [seeds]
macro-paths: [macros]
snapshot-paths: [snapshots]

target-path: target
clean-targets:
- target
- dbt_packages

vars:
  mojo:
    timestamp_tolerance_mins: 5

models:
  mojo:
    # this is based on dbt's documented structure
    # https://docs.getdbt.com/guides/best-practices/how-we-structure/1-guide-overview

# DJ 2024/02/06 using merge strategy as i don't have knowledge of partitions
#               insert overwrite could be quicker / cheaper, would need testing
    marts:
      +materialized: incremental
      +incremental_strategy: merge

    staging:
      +schema: staging
      +materialized: incremental
      +incremental_strategy: merge
